theme: jekyll-theme-midnight
title: "RECS Project"
description: "Blog about architecture."
gitorg: "https://github.com/jm1021/leuck_reunion"
description: "By: Sachit, Raunak, Edwin, and Colin"
google_analytics:

remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one